### ISSUE TITLE
Cant install on ubuntu 22.04 with pip

### ISSUE THREAD

**Issue by maxpaynebupt** [Ciphey/Ciphey#754]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
Installation with pip in ubuntu 22.04 failed while installing scipy==1.4.1

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
NA
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: [e.g. Windows, Debian 11.0, Arch, OS X El Capitan]   Ubuntu 22.04.1 LTS  (WSL)
 - Python version: [python3 --version]   3.10.6
 - Ciphey versions: [python3 -m pip show ciphey cipheycore cipheydists]  5.14.0
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**

Collecting scipy==1.4.1
  Downloading https://mirrors.aliyun.com/pypi/simple/scipy/scipy-1.4.1.tar.gz (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 57.7 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3490 lines of output]
      Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
      Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting wheel
        Downloading https://mirrors.aliyun.com/pypi/simple/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools
        Downloading https://mirrors.aliyun.com/pypi/simple/packages/d5/e6/e3a70a77dda22766b9ef4ff47ff8320720311e78d11d1401baffca3f6879/setuptools-65.4.0-py3-none-any.whl (1.2 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 29.7 MB/s eta 0:00:00
      Collecting Cython>=0.29.13
        Downloading https://mirrors.aliyun.com/pypi/simple/packages/92/74/e3be5e08a6cf55eae64a7a64fdef7a7f77cb0cdd10e4689b60b3a131bf76/Cython-0.29.32-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 52.2 MB/s eta 0:00:00
      Collecting numpy==1.17.3
        Downloading https://mirrors.aliyun.com/pypi/simple/packages/b6/d6/be8f975f5322336f62371c9abeb936d592c98c047ad63035f1b38ae08efe/numpy-1.17.3.zip (6.4 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 75.7 MB/s eta 0:00:00
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pybind11>=2.4.0
        Downloading https://mirrors.aliyun.com/pypi/simple/packages/9a/7f/855560aa568e50bea6012ed535e6b8c436e99394f3e5a649d44d2e557242/pybind11-2.10.0-py3-none-any.whl (213 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.3/213.3 KB 26.7 MB/s eta 0:00:00
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): still running...
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [2924 lines of output]
            Running from numpy source directory.
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE

            blis_info:
            customize UnixCCompiler
              libraries blis not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE

            openblas_info:
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/usr/lib/x86_64-linux-gnu']
                language = c
                define_macros = [('HAVE_CBLAS', None)]

              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/usr/lib/x86_64-linux-gnu']
                language = c
                define_macros = [('HAVE_CBLAS', None)]

            /bin/sh: 1: svnversion: not found
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE

            openblas_lapack_info:
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
            C compiler: x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

            creating /tmp/tmpux76_j6x/tmp
            creating /tmp/tmpux76_j6x/tmp/tmpux76_j6x
            compile options: '-c'
            x86_64-linux-gnu-gcc: /tmp/tmpux76_j6x/source.c
            x86_64-linux-gnu-gcc /tmp/tmpux76_j6x/tmp/tmpux76_j6x/source.o -lopenblas -o /tmp/tmpux76_j6x/a.out
            customize UnixCCompiler
              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/usr/lib/x86_64-linux-gnu']
                language = c
                define_macros = [('HAVE_CBLAS', None)]

              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/usr/lib/x86_64-linux-gnu']
                language = c
                define_macros = [('HAVE_CBLAS', None)]

            /usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.linux-x86_64-3.1
            creating build/src.linux-x86_64-3.1/numpy
            creating build/src.linux-x86_64-3.1/numpy/distutils
            building library "npymath" sources
            get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
            customize Gnu95FCompiler
            Could not locate executable gfortran
            Could not locate executable f95
            customize IntelFCompiler
            Could not locate executable ifort
            Could not locate executable ifc
            customize LaheyFCompiler
            Could not locate executable lf95
            customize PGroupFCompiler
            Could not locate executable pgfortran
            customize AbsoftFCompiler
            Could not locate executable f90
            Could not locate executable f77
            customize NAGFCompiler
            customize VastFCompiler
            customize CompaqFCompiler
            Could not locate executable fort
            customize IntelItaniumFCompiler
            Could not locate executable efort
            Could not locate executable efc
            customize IntelEM64TFCompiler
            customize GnuFCompiler
            Could not locate executable g77
            customize G95FCompiler
            Could not locate executable g95
            customize PathScaleFCompiler
            Could not locate executable pathf95
            customize NAGFORCompiler
            Could not locate executable nagfor
            don't know how to compile Fortran code on platform 'posix'
            C compiler: x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.10 -c'
            x86_64-linux-gnu-gcc: _configtest.c
            x86_64-linux-gnu-gcc _configtest.o -o _configtest
            success!
            removing: _configtest.c _configtest.o _configtest.o.d _configtest
            C compiler: x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.10 -c'
            x86_64-linux-gnu-gcc: _configtest.c
            _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’; expected ‘double(double)’ [-Wbuiltin-declaration-mismatch]
                1 | int exp (void);
                  |     ^~~
            _configtest.c:1:1: note: ‘exp’ is declared in header ‘<math.h>’
              +++ |+#include <math.h>
                1 | int exp (void);
            x86_64-linux-gnu-gcc _configtest.o -o _configtest
            /usr/bin/ld: _configtest.o: in function `main':
            /tmp/pip-install-fm_k9ka8/numpy_00de008c4824471f86811bdcade113bf/_configtest.c:6: undefined reference to `exp'
            collect2: error: ld returned 1 exit status
            failure.
            removing: _configtest.c _configtest.o _configtest.o.d

**To Reproduce**
1. What input did you use?   pip install ciphey
2. What flags / arguments did you use? None

**Expected behavior**

**Any other information?**

**Comment by SkeletalDemise** [comment]
Ciphey doesn't work with Python 3.10, use Python 3.9 on Linux.

**Comment by ad0nis** [comment]
@SkeletalDemise: Is the plan to never support newer versions of python? On the distro I'm on, I can only install 3.10 and 3.11 without going through pyenv or manually installing older versions. Doesn't seem very forward-looking - are there specific issues that make this difficult?

**Comment by bee-san** [comment]
> @SkeletalDemise: Is the plan to never support newer versions of python?

Yes, this is the plan. We are deprecating Ciphey in favour of our Rust rewrite which does support all operating systems 😅 
https://github.com/Ciphey/Ciphey/issues/764
