### ISSUE TITLE
TypeError: Identifier.identify()

### ISSUE THREAD

**Issue by NA3** [Ciphey/Ciphey#721]
**Describe the bug**
verbose stop on Trying PyWhat checker
TypeError: Identifier.identify() got an unexpected keyword argument 'api'

**Plaintext**
```
Issue when using ciphey on a blackarch os
ciphey have be instaled with yay -S ciphey

```
**Version**
 - OS/Distro: Linux blackarch 5.16.1-arch1-1
 - Python 3.10.2
 - Ciphey 5.14.0
 - Cipheycore 0.3.2
 - Cipheydists 0.3.35
 - no docker

**Verbose Output*
![image](https://user-images.githubusercontent.com/3059879/150697804-aa95ef94-186a-4f46-b9ee-3f299f762dc1.png)
![image](https://user-images.githubusercontent.com/3059879/150697816-52f87ae7-53cc-41c6-bb70-2eaca35cd208.png)

**To Reproduce**

ciphey -t 'YXNkZmdoamtsMTIzNDU2Nzg5MA=='  -vvv
have the same error when using a file on input

**Comment by NA3** [comment]
i have try to install cipey on a fresh arch wsl2 environment, and it fail cause on numpy and absl-py
the eror with numpy have pass afert install it with yay but alway the eror for absl-py

![image](https://user-images.githubusercontent.com/3059879/150719236-1256e75c-6815-43fb-96f0-2d8e2c095a89.png)
![image](https://user-images.githubusercontent.com/3059879/150719187-17ef056b-bb41-44d5-8de0-6300573bdba6.png)

Regards.

**Comment by SkeletalDemise** [comment]
Hello. I'm closing this because it's not a bug, Ciphey doesn't work with Python 3.10. Please use Python 3.7, 3.8, or 3.9 (if using Linux.)
Look at the installation instructions for more help: https://github.com/Ciphey/Ciphey/wiki/Installation

**Comment by r1ght0us** [comment]
@SkeletalDemise Hello, I also encountered this problem in python3.8.5
![image](https://user-images.githubusercontent.com/30382389/180209735-22e2ef3a-c503-42b9-b168-a46ecfa17629.png)

**Comment by amobaishi** [comment]
python 3.8.10
![image](https://user-images.githubusercontent.com/39741298/218346122-c69977ba-acae-4253-944b-c3318fbae0e7.png)

**Comment by loobug** [comment]
pip install pywhat==1.2.0 ,can fix this bug

**Comment by h4m5t** [comment]
> 

It works!

**Comment by Tb2019** [comment]
> pip install pywhat==1.2.0 ,can fix this bug

it works
